// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASWYH3gSFidiQxtCP2zftFSvsJo3vYbNM',
    appId: '1:621627479609:web:92af8da281accce5845fe8',
    messagingSenderId: '621627479609',
    projectId: 'reminderapp-47d49',
    authDomain: 'reminderapp-47d49.firebaseapp.com',
    storageBucket: 'reminderapp-47d49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO4RygsIJScKHMyaWLM4lGIgRKiAGAuPI',
    appId: '1:621627479609:android:af8e3c7e5e7f90f6845fe8',
    messagingSenderId: '621627479609',
    projectId: 'reminderapp-47d49',
    storageBucket: 'reminderapp-47d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4b7PSakdGd00pvVMciJduUNqQJJSuJKg',
    appId: '1:621627479609:ios:97302d54832ee1a4845fe8',
    messagingSenderId: '621627479609',
    projectId: 'reminderapp-47d49',
    storageBucket: 'reminderapp-47d49.appspot.com',
    iosBundleId: 'com.example.reminderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4b7PSakdGd00pvVMciJduUNqQJJSuJKg',
    appId: '1:621627479609:ios:24890971c29a1650845fe8',
    messagingSenderId: '621627479609',
    projectId: 'reminderapp-47d49',
    storageBucket: 'reminderapp-47d49.appspot.com',
    iosBundleId: 'com.example.reminderapp.RunnerTests',
  );
}
